import { Bonus, SourceCategory, Tiers } from './bonus';
import { Stat, Stats } from './stat';

export enum ResearchTechName {
    AttackTacticsI       = 'Attack Tactics I',
    AttackTacticsII      = 'Attack Tactics II',
    AttackTacticsIII     = 'Attack Tactics III',
    AttackTacticsIV      = 'Attack Tactics IV',
    AttackTacticsV       = 'Attack Tactics V',
    AttackTacticsVI      = 'Attack Tactics VI',
    BattleDressingI      = 'Battle Dressing I',
    BattleDressingII     = 'Battle Dressing II',
    BattleDressingIII    = 'Battle Dressing III',
    BattleDressingIV     = 'Battle Dressing IV',
    BattleDressingV      = 'Battle Dressing V',
    BattleDressingVI     = 'Battle Dressing VI',
    BattleDressingVII    = 'Battle Dressing VII',
    ChargeStrategyI      = 'Charge Strategy I',
    ChargeStrategyII     = 'Charge Strategy II',
    ChargeStrategyIII    = 'Charge Strategy III',
    ChargeStrategyIV     = 'Charge Strategy IV',
    ChargeStrategyV      = 'Charge Strategy V',
    ChargeStrategyVI     = 'Charge Strategy VI',
    CloseCombatI         = 'Close Combat I',
    CloseCombatII        = 'Close Combat II',
    CloseCombatIII       = 'Close Combat III',
    CloseCombatIV        = 'Close Combat IV',
    CloseCombatV         = 'Close Combat V',
    CloseCombatVI        = 'Close Combat VI',
    DefenseFormationsI   = 'Defense Formations I',
    DefenseFormationsII  = 'Defense Formations II',
    DefenseFormationsIII = 'Defense Formations III',
    DefenseFormationsIV  = 'Defense Formations IV',
    DefenseFormationsV   = 'Defense Formations V',
    DefenseFormationsVI  = 'Defense Formations VI',
    FertilizerTechI      = 'Fertilizer Tech I',
    FertilizerTechII     = 'Fertilizer Tech II',
    FertilizerTechIII    = 'Fertilizer Tech III',
    FertilizerTechIV     = 'Fertilizer Tech IV',
    FertilizerTechV      = 'Fertilizer Tech V',
    FertilizerTechVI     = 'Fertilizer Tech VI',
    FoodHaulageI         = 'Food Haulage I',
    FoodHaulageII        = 'Food Haulage II',
    FoodHaulageIII       = 'Food Haulage III',
    FoodHaulageIV        = 'Food Haulage IV',
    FoodHaulageV         = 'Food Haulage V',
    FoodHaulageVI        = 'Food Haulage VI',
    GasHaulageI          = 'Gas Haulage I',
    GasHaulageII         = 'Gas Haulage II',
    GasHaulageIII        = 'Gas Haulage III',
    GasHaulageIV         = 'Gas Haulage IV',
    GasHaulageV          = 'Gas Haulage V',
    GunsBlazingI         = 'Guns Blazing I',
    GunsBlazingII        = 'Guns Blazing II',
    GunsBlazingIII       = 'Guns Blazing III',
    GunsBlazingIV        = 'Guns Blazing IV',
    GunsBlazingV         = 'Guns Blazing V',
    GunsBlazingVI        = 'Guns Blazing VI',
    HunterDefenseI       = 'Hunter Defense I',
    HunterDefenseII      = 'Hunter Defense II',
    HunterDefenseIII     = 'Hunter Defense III',
    HunterDefenseIV      = 'Hunter Defense IV',
    HunterDefenseV       = 'Hunter Defense V',
    HunterDefenseVI      = 'Hunter Defense VI',
    HunterProtectionI    = 'Hunter Protection I',
    HunterProtectionII   = 'Hunter Protection II',
    HunterProtectionIII  = 'Hunter Protection III',
    HunterProtectionIV   = 'Hunter Protection IV',
    HunterProtectionV    = 'Hunter Protection V',
    HunterProtectionVI   = 'Hunter Protection VI',
    LeadershipI          = 'Leadership I',
    LeadershipII         = 'Leadership II',
    LeadershipIII        = 'Leadership III',
    LeadershipIV         = 'Leadership IV',
    LoggingTechI         = 'Logging Tech I',
    LoggingTechII        = 'Logging Tech II',
    LoggingTechIII       = 'Logging Tech III',
    LoggingTechIV        = 'Logging Tech IV',
    LoggingTechV         = 'Logging Tech V',
    LoggingTechVI        = 'Logging Tech VI',
    MarchCapacityI       = 'March Capacity I',
    MarchCapacityII      = 'March Capacity II',
    MarchCapacityIII     = 'March Capacity III',
    MarchCapacityIV      = 'March Capacity IV',
    MarchCapacityV       = 'March Capacity V',
    MarchCapacityVI      = 'March Capacity VI',
    MasterMechanicI      = 'Master Mechanic I',
    MasterMechanicII     = 'Master Mechanic II',
    MasterMechanicIII    = 'Master Mechanic III',
    MasterMechanicIV     = 'Master Mechanic IV',
    MasterMechanicV      = 'Master Mechanic V',
    MasterMechanicVI     = 'Master Mechanic VI',
    MeleeDefenseI        = 'Melee Defense I',
    MeleeDefenseII       = 'Melee Defense II',
    MeleeDefenseIII      = 'Melee Defense III',
    MeleeDefenseIV       = 'Melee Defense IV',
    MeleeDefenseV        = 'Melee Defense V',
    MeleeDefenseVI       = 'Melee Defense VI',
    MetalHaulageI        = 'Metal Haulage I',
    MetalHaulageII       = 'Metal Haulage II',
    MetalHaulageIII      = 'Metal Haulage III',
    MetalHaulageIV       = 'Metal Haulage IV',
    MetalHaulageV        = 'Metal Haulage V',
    MobileAssaultI       = 'Mobile Assault I',
    MobileAssaultII      = 'Mobile Assault II',
    MobileAssaultIII     = 'Mobile Assault III',
    MobileAssaultIV      = 'Mobile Assault IV',
    MobileAssaultV       = 'Mobile Assault V',
    MobileAssaultVI      = 'Mobile Assault VI',
    MoreBedsI            = 'More Beds I',
    MoreBedsII           = 'More Beds II',
    MoreBedsIII          = 'More Beds III',
    MoreBedsIV           = 'More Beds IV',
    MoreBedsV            = 'More Beds V',
    MoreBedsVI           = 'More Beds VI',
    MoreBedsVII          = 'More Beds VII',
    OilDrumsI            = 'Oil Drums I',
    OilDrumsII           = 'Oil Drums II',
    OilDrumsIII          = 'Oil Drums III',
    OilDrumsIV           = 'Oil Drums IV',
    OilDrumsV            = 'Oil Drums V',
    PrecisionStrikeI     = 'Precision Strike I',
    PrecisionStrikeII    = 'Precision Strike II',
    PrecisionStrikeIII   = 'Precision Strike III',
    PrecisionStrikeIV    = 'Precision Strike IV',
    PrecisionStrikeV     = 'Precision Strike V',
    PrecisionStrikeVI    = 'Precision Strike VI',
    RiderDefenseI        = 'Rider Defense I',
    RiderDefenseII       = 'Rider Defense II',
    RiderDefenseIII      = 'Rider Defense III',
    RiderDefenseIV       = 'Rider Defense IV',
    RiderDefenseV        = 'Rider Defense V',
    RiderDefenseVI       = 'Rider Defense VI',
    ShieldImprovementI   = 'Shield Improvement I',
    ShieldImprovementII  = 'Shield Improvement II',
    ShieldImprovementIII = 'Shield Improvement III',
    ShieldImprovementIV  = 'Shield Improvement IV',
    ShieldImprovementV   = 'Shield Improvement V',
    ShieldImprovementVI  = 'Shield Improvement VI',
    ShoottoKillI         = 'Shoot to Kill I',
    ShoottoKillII        = 'Shoot to Kill II',
    ShoottoKillIII       = 'Shoot to Kill III',
    ShoottoKillIV        = 'Shoot to Kill IV',
    ShoottoKillV         = 'Shoot to Kill V',
    ShoottoKillVI        = 'Shoot to Kill VI',
    SortingTechI         = 'Sorting Tech I',
    SortingTechII        = 'Sorting Tech II',
    SortingTechIII       = 'Sorting Tech III',
    SortingTechIV        = 'Sorting Tech IV',
    SortingTechV         = 'Sorting Tech V',
    SteadyShotI          = 'Steady Shot I',
    SteadyShotII         = 'Steady Shot II',
    SteadyShotIII        = 'Steady Shot III',
    SteadyShotIV         = 'Steady Shot IV',
    SteadyShotV          = 'Steady Shot V',
    SteadyShotVI         = 'Steady Shot VI',
    SupplyConvoyI        = 'Supply Convoy I',
    SupplyConvoyII       = 'Supply Convoy II',
    SupplyConvoyIII      = 'Supply Convoy III',
    SupplyConvoyIV       = 'Supply Convoy IV',
    SupplyConvoyV        = 'Supply Convoy V',
    SurvivalTrainingI    = 'Survival Training I',
    SurvivalTrainingII   = 'Survival Training II',
    SurvivalTrainingIII  = 'Survival Training III',
    SurvivalTrainingIV   = 'Survival Training IV',
    SurvivalTrainingV    = 'Survival Training V',
    SurvivalTrainingVI   = 'Survival Training VI',
    TechImprovementI     = 'Tech Improvement I',
    TechImprovementII    = 'Tech Improvement II',
    TechImprovementIII   = 'Tech Improvement III',
    TechImprovementIV    = 'Tech Improvement IV',
    TechImprovementV     = 'Tech Improvement V',
    TechImprovementVI    = 'Tech Improvement VI',
    TechImprovementVII   = 'Tech Improvement VII',
    ToolImprovementI     = 'Tool Improvement I',
    ToolImprovementII    = 'Tool Improvement II',
    ToolImprovementIII   = 'Tool Improvement III',
    ToolImprovementIV    = 'Tool Improvement IV',
    ToolImprovementV     = 'Tool Improvement V',
    ToolImprovementVI    = 'Tool Improvement VI',
    ToolImprovementVII   = 'Tool Improvement VII',
    TrainingRoutinesI    = 'Training Routines I',
    TrainingRoutinesII   = 'Training Routines II',
    TrainingRoutinesIII  = 'Training Routines III',
    TrainingRoutinesIV   = 'Training Routines IV',
    TrainingRoutinesV    = 'Training Routines V',
    TrainingRoutinesVI   = 'Training Routines VI',
    TrainingRoutinesVII  = 'Training Routines VII',
    TrainingYardI        = 'Training Yard I',
    TrainingYardII       = 'Training Yard II',
    TrainingYardIII      = 'Training Yard III',
    TrainingYardIV       = 'Training Yard IV',
    TrainingYardV        = 'Training Yard V',
    TrainingYardVI       = 'Training Yard VI',
    TrainingYardVII      = 'Training Yard VII',
    WoodHaulageI         = 'Wood Haulage I',
    WoodHaulageII        = 'Wood Haulage II',
    WoodHaulageIII       = 'Wood Haulage III',
    WoodHaulageIV        = 'Wood Haulage IV',
    WoodHaulageV         = 'Wood Haulage V',
    WoodHaulageVI        = 'Wood Haulage VI'
}

export class ResearchTech {
    readonly name: ResearchTechName;
    readonly stat: Stat;
    readonly levels: ResearchTechLevel[];

    constructor(name: ResearchTechName, stat: Stat, ...levelData: number[]) {
        this.name = name;
        this.stat = stat;
        this.levels = levelData.map((bonusValue, i) => new ResearchTechLevel(this, i + 1, bonusValue));
    }
}

export class ResearchTechLevel {
    readonly tech: ResearchTech;
    readonly level: number;
    readonly bonuses: Bonus[];

    constructor(tech: ResearchTech, level: number, bonusValue: number) {
        this.tech = tech;
        this.level = level;
        this.bonuses = [ new Bonus(tech.stat, bonusValue, this) ];
    }

    get name() {
        return this.tech.name + ' ' + String(this.level);
    }

    get category() {
        return SourceCategory.Research;
    }

    get tier() {
        return Tiers.Common;
    }
}

export const ResearchTechs = {
    [ResearchTechName.AttackTacticsI]: new ResearchTech(ResearchTechName.AttackTacticsI, Stats.TroopAttack, 50,50,50),
    [ResearchTechName.AttackTacticsII]: new ResearchTech(ResearchTechName.AttackTacticsII, Stats.TroopAttack, 75,75,100),
    [ResearchTechName.AttackTacticsIII]: new ResearchTech(ResearchTechName.AttackTacticsIII, Stats.TroopAttack, 100,100,100,150),
    [ResearchTechName.AttackTacticsIV]: new ResearchTech(ResearchTechName.AttackTacticsIV, Stats.TroopAttack, 175,175,175,175,300),
    [ResearchTechName.AttackTacticsV]: new ResearchTech(ResearchTechName.AttackTacticsV, Stats.TroopAttack, 200,200,200,200,200,350),
    [ResearchTechName.AttackTacticsVI]: new ResearchTech(ResearchTechName.AttackTacticsVI, Stats.TroopAttack, 127,127,127,127,127,128,127,127,127,127,127,127),
    [ResearchTechName.BattleDressingI]: new ResearchTech(ResearchTechName.BattleDressingI, Stats.HealingSpeed, 460,920,1520),
    [ResearchTechName.BattleDressingII]: new ResearchTech(ResearchTechName.BattleDressingII, Stats.HealingSpeed, 900,1800,3000),
    [ResearchTechName.BattleDressingIII]: new ResearchTech(ResearchTechName.BattleDressingIII, Stats.HealingSpeed, 1340,2680,4480),
    [ResearchTechName.BattleDressingIV]: new ResearchTech(ResearchTechName.BattleDressingIV, Stats.HealingSpeed, 1800,3600,6000),
    [ResearchTechName.BattleDressingV]: new ResearchTech(ResearchTechName.BattleDressingV, Stats.HealingSpeed, 2240,4480,7480),
    [ResearchTechName.BattleDressingVI]: new ResearchTech(ResearchTechName.BattleDressingVI, Stats.HealingSpeed, 2700,5400,9000),
    [ResearchTechName.BattleDressingVII]: new ResearchTech(ResearchTechName.BattleDressingVII, Stats.HealingSpeed, 2700,5400,9000),
    [ResearchTechName.ChargeStrategyI]: new ResearchTech(ResearchTechName.ChargeStrategyI, Stats.RiderLethality, 125,125,150),
    [ResearchTechName.ChargeStrategyII]: new ResearchTech(ResearchTechName.ChargeStrategyII, Stats.RiderLethality, 175,175,200),
    [ResearchTechName.ChargeStrategyIII]: new ResearchTech(ResearchTechName.ChargeStrategyIII, Stats.RiderLethality, 250,250,250,400),
    [ResearchTechName.ChargeStrategyIV]: new ResearchTech(ResearchTechName.ChargeStrategyIV, Stats.RiderLethality, 400,400,400,400,650),
    [ResearchTechName.ChargeStrategyV]: new ResearchTech(ResearchTechName.ChargeStrategyV, Stats.RiderLethality, 475,475,475,475,475,800),
    [ResearchTechName.ChargeStrategyVI]: new ResearchTech(ResearchTechName.ChargeStrategyVI, Stats.RiderLethality, 304,304,305,304,304,304,304,304,305,304,304,304),
    [ResearchTechName.CloseCombatI]: new ResearchTech(ResearchTechName.CloseCombatI, Stats.InfantryLethality, 125,125,150),
    [ResearchTechName.CloseCombatII]: new ResearchTech(ResearchTechName.CloseCombatII, Stats.InfantryLethality, 175,175,200),
    [ResearchTechName.CloseCombatIII]: new ResearchTech(ResearchTechName.CloseCombatIII, Stats.InfantryLethality, 250,250,250,400),
    [ResearchTechName.CloseCombatIV]: new ResearchTech(ResearchTechName.CloseCombatIV, Stats.InfantryLethality, 400,400,400,400,650),
    [ResearchTechName.CloseCombatV]: new ResearchTech(ResearchTechName.CloseCombatV, Stats.InfantryLethality, 475,475,475,475,475,800),
    [ResearchTechName.CloseCombatVI]: new ResearchTech(ResearchTechName.CloseCombatVI, Stats.InfantryLethality, 304,304,305,304,304,304,304,304,305,304,304,304),
    [ResearchTechName.DefenseFormationsI]: new ResearchTech(ResearchTechName.DefenseFormationsI, Stats.TroopDefense, 50,50,50),
    [ResearchTechName.DefenseFormationsII]: new ResearchTech(ResearchTechName.DefenseFormationsII, Stats.TroopDefense, 75,75,100),
    [ResearchTechName.DefenseFormationsIII]: new ResearchTech(ResearchTechName.DefenseFormationsIII, Stats.TroopDefense, 100,100,100,150),
    [ResearchTechName.DefenseFormationsIV]: new ResearchTech(ResearchTechName.DefenseFormationsIV, Stats.TroopDefense, 175,175,175,175,300),
    [ResearchTechName.DefenseFormationsV]: new ResearchTech(ResearchTechName.DefenseFormationsV, Stats.TroopDefense, 200,200,200,200,200,350),
    [ResearchTechName.DefenseFormationsVI]: new ResearchTech(ResearchTechName.DefenseFormationsVI, Stats.TroopDefense, 127,127,127,127,127,128,127,127,127,127,127,127),
    [ResearchTechName.FertilizerTechI]: new ResearchTech(ResearchTechName.FertilizerTechI, Stats.FoodProductionSpeed, 800,1600,2700),
    [ResearchTechName.FertilizerTechII]: new ResearchTech(ResearchTechName.FertilizerTechII, Stats.FoodProductionSpeed, 800,1600,2700),
    [ResearchTechName.FertilizerTechIII]: new ResearchTech(ResearchTechName.FertilizerTechIII, Stats.FoodProductionSpeed, 1100,2200,3650),
    [ResearchTechName.FertilizerTechIV]: new ResearchTech(ResearchTechName.FertilizerTechIV, Stats.FoodProductionSpeed, 1350,2700,4500),
    [ResearchTechName.FertilizerTechV]: new ResearchTech(ResearchTechName.FertilizerTechV, Stats.FoodProductionSpeed, 1600,3200,5350),
    [ResearchTechName.FertilizerTechVI]: new ResearchTech(ResearchTechName.FertilizerTechVI, Stats.FoodProductionSpeed, 1600,3200,5350),
    [ResearchTechName.FoodHaulageI]: new ResearchTech(ResearchTechName.FoodHaulageI, Stats.FoodGatheringSpeed, 800,1600,2700),
    [ResearchTechName.FoodHaulageII]: new ResearchTech(ResearchTechName.FoodHaulageII, Stats.FoodGatheringSpeed, 800,1600,2700),
    [ResearchTechName.FoodHaulageIII]: new ResearchTech(ResearchTechName.FoodHaulageIII, Stats.FoodGatheringSpeed, 1100,2200,3650),
    [ResearchTechName.FoodHaulageIV]: new ResearchTech(ResearchTechName.FoodHaulageIV, Stats.FoodGatheringSpeed, 1350,2700,4500),
    [ResearchTechName.FoodHaulageV]: new ResearchTech(ResearchTechName.FoodHaulageV, Stats.FoodGatheringSpeed, 1600,3200,5350),
    [ResearchTechName.FoodHaulageVI]: new ResearchTech(ResearchTechName.FoodHaulageVI, Stats.FoodGatheringSpeed, 1600,3200,5350),
    [ResearchTechName.GasHaulageI]: new ResearchTech(ResearchTechName.GasHaulageI, Stats.GasGatheringSpeed, 1600,3200,5350),
    [ResearchTechName.GasHaulageII]: new ResearchTech(ResearchTechName.GasHaulageII, Stats.GasGatheringSpeed, 1100,2200,3650),
    [ResearchTechName.GasHaulageIII]: new ResearchTech(ResearchTechName.GasHaulageIII, Stats.GasGatheringSpeed, 1350,2700,4500),
    [ResearchTechName.GasHaulageIV]: new ResearchTech(ResearchTechName.GasHaulageIV, Stats.GasGatheringSpeed, 1600,3200,5350),
    [ResearchTechName.GasHaulageV]: new ResearchTech(ResearchTechName.GasHaulageV, Stats.GasGatheringSpeed, 1600,3200,5350),
    [ResearchTechName.GunsBlazingI]: new ResearchTech(ResearchTechName.GunsBlazingI, Stats.InfantryAttack, 125,125,150),
    [ResearchTechName.GunsBlazingII]: new ResearchTech(ResearchTechName.GunsBlazingII, Stats.InfantryAttack, 175,175,200),
    [ResearchTechName.GunsBlazingIII]: new ResearchTech(ResearchTechName.GunsBlazingIII, Stats.InfantryAttack, 250,250,250,400),
    [ResearchTechName.GunsBlazingIV]: new ResearchTech(ResearchTechName.GunsBlazingIV, Stats.InfantryAttack, 400,400,400,400,650),
    [ResearchTechName.GunsBlazingV]: new ResearchTech(ResearchTechName.GunsBlazingV, Stats.InfantryAttack, 475,475,475,475,475,800),
    [ResearchTechName.GunsBlazingVI]: new ResearchTech(ResearchTechName.GunsBlazingVI, Stats.InfantryAttack, 304,304,305,304,304,304,304,304,305,304,304,304),
    [ResearchTechName.HunterDefenseI]: new ResearchTech(ResearchTechName.HunterDefenseI, Stats.HunterDefense, 125,125,150),
    [ResearchTechName.HunterDefenseII]: new ResearchTech(ResearchTechName.HunterDefenseII, Stats.HunterDefense, 175,175,200),
    [ResearchTechName.HunterDefenseIII]: new ResearchTech(ResearchTechName.HunterDefenseIII, Stats.HunterDefense, 250,250,250,400),
    [ResearchTechName.HunterDefenseIV]: new ResearchTech(ResearchTechName.HunterDefenseIV, Stats.HunterDefense, 400,400,400,400,650),
    [ResearchTechName.HunterDefenseV]: new ResearchTech(ResearchTechName.HunterDefenseV, Stats.HunterDefense, 475,475,475,475,475,800),
    [ResearchTechName.HunterDefenseVI]: new ResearchTech(ResearchTechName.HunterDefenseVI, Stats.HunterDefense, 304,304,305,304,304,304,304,304,305,304,304,304),
    [ResearchTechName.HunterProtectionI]: new ResearchTech(ResearchTechName.HunterProtectionI, Stats.HunterHealth, 125,125,150),
    [ResearchTechName.HunterProtectionII]: new ResearchTech(ResearchTechName.HunterProtectionII, Stats.HunterHealth, 175,175,200),
    [ResearchTechName.HunterProtectionIII]: new ResearchTech(ResearchTechName.HunterProtectionIII, Stats.HunterHealth, 250,250,250,400),
    [ResearchTechName.HunterProtectionIV]: new ResearchTech(ResearchTechName.HunterProtectionIV, Stats.HunterHealth, 400,400,400,400,650),
    [ResearchTechName.HunterProtectionV]: new ResearchTech(ResearchTechName.HunterProtectionV, Stats.HunterHealth, 475,475,475,475,475,800),
    [ResearchTechName.HunterProtectionVI]: new ResearchTech(ResearchTechName.HunterProtectionVI, Stats.HunterHealth, 304,304,305,304,304,304,304,304,305,304,304,304),
    [ResearchTechName.LeadershipI]: new ResearchTech(ResearchTechName.LeadershipI, Stats.MarchCount, 1),
    [ResearchTechName.LeadershipII]: new ResearchTech(ResearchTechName.LeadershipII, Stats.MarchCount, 1),
    [ResearchTechName.LeadershipIII]: new ResearchTech(ResearchTechName.LeadershipIII, Stats.MarchCount, 1),
    [ResearchTechName.LeadershipIV]: new ResearchTech(ResearchTechName.LeadershipIV, Stats.MarchCount, 1),
    [ResearchTechName.LoggingTechI]: new ResearchTech(ResearchTechName.LoggingTechI, Stats.WoodProductionSpeed, 800,1600,2700),
    [ResearchTechName.LoggingTechII]: new ResearchTech(ResearchTechName.LoggingTechII, Stats.WoodProductionSpeed, 800,1600,2700),
    [ResearchTechName.LoggingTechIII]: new ResearchTech(ResearchTechName.LoggingTechIII, Stats.WoodProductionSpeed, 1100,2200,3650),
    [ResearchTechName.LoggingTechIV]: new ResearchTech(ResearchTechName.LoggingTechIV, Stats.WoodProductionSpeed, 1350,2700,4500),
    [ResearchTechName.LoggingTechV]: new ResearchTech(ResearchTechName.LoggingTechV, Stats.WoodProductionSpeed, 1600,3200,5350),
    [ResearchTechName.LoggingTechVI]: new ResearchTech(ResearchTechName.LoggingTechVI, Stats.WoodProductionSpeed, 1600,3200,5350),
    [ResearchTechName.MarchCapacityI]: new ResearchTech(ResearchTechName.MarchCapacityI, Stats.MarchCapacity, 320,320,430),
    [ResearchTechName.MarchCapacityII]: new ResearchTech(ResearchTechName.MarchCapacityII, Stats.MarchCapacity, 430,430,570),
    [ResearchTechName.MarchCapacityIII]: new ResearchTech(ResearchTechName.MarchCapacityIII, Stats.MarchCapacity, 620,620,620,990),
    [ResearchTechName.MarchCapacityIV]: new ResearchTech(ResearchTechName.MarchCapacityIV, Stats.MarchCapacity, 990,990,990,990,1700),
    [ResearchTechName.MarchCapacityV]: new ResearchTech(ResearchTechName.MarchCapacityV, Stats.MarchCapacity, 1200,1200,1200,1200,1200,2000),
    [ResearchTechName.MarchCapacityVI]: new ResearchTech(ResearchTechName.MarchCapacityVI, Stats.MarchCapacity, 2000,2000,2000,2000,2000,3400),
    [ResearchTechName.MasterMechanicI]: new ResearchTech(ResearchTechName.MasterMechanicI, Stats.RiderHealth, 125,125,150),
    [ResearchTechName.MasterMechanicII]: new ResearchTech(ResearchTechName.MasterMechanicII, Stats.RiderHealth, 175,175,200),
    [ResearchTechName.MasterMechanicIII]: new ResearchTech(ResearchTechName.MasterMechanicIII, Stats.RiderHealth, 250,250,250,400),
    [ResearchTechName.MasterMechanicIV]: new ResearchTech(ResearchTechName.MasterMechanicIV, Stats.RiderHealth, 400,400,400,400,650),
    [ResearchTechName.MasterMechanicV]: new ResearchTech(ResearchTechName.MasterMechanicV, Stats.RiderHealth, 475,475,475,475,475,800),
    [ResearchTechName.MasterMechanicVI]: new ResearchTech(ResearchTechName.MasterMechanicVI, Stats.RiderHealth, 304,304,305,304,304,304,304,304,305,304,304,304),
    [ResearchTechName.MeleeDefenseI]: new ResearchTech(ResearchTechName.MeleeDefenseI, Stats.InfantryDefense, 125,125,150),
    [ResearchTechName.MeleeDefenseII]: new ResearchTech(ResearchTechName.MeleeDefenseII, Stats.InfantryDefense, 175,175,200),
    [ResearchTechName.MeleeDefenseIII]: new ResearchTech(ResearchTechName.MeleeDefenseIII, Stats.InfantryDefense, 250,250,250,400),
    [ResearchTechName.MeleeDefenseIV]: new ResearchTech(ResearchTechName.MeleeDefenseIV, Stats.InfantryDefense, 400,400,400,400,650),
    [ResearchTechName.MeleeDefenseV]: new ResearchTech(ResearchTechName.MeleeDefenseV, Stats.InfantryDefense, 475,475,475,475,475,800),
    [ResearchTechName.MeleeDefenseVI]: new ResearchTech(ResearchTechName.MeleeDefenseVI, Stats.InfantryDefense, 304,304,305,304,304,304,304,304,305,304,304,304),
    [ResearchTechName.MetalHaulageI]: new ResearchTech(ResearchTechName.MetalHaulageI, Stats.MetalGatheringSpeed, 1600,3200,5350),
    [ResearchTechName.MetalHaulageII]: new ResearchTech(ResearchTechName.MetalHaulageII, Stats.MetalGatheringSpeed, 1100,2200,3650),
    [ResearchTechName.MetalHaulageIII]: new ResearchTech(ResearchTechName.MetalHaulageIII, Stats.MetalGatheringSpeed, 1350,2700,4500),
    [ResearchTechName.MetalHaulageIV]: new ResearchTech(ResearchTechName.MetalHaulageIV, Stats.MetalGatheringSpeed, 1600,3200,5350),
    [ResearchTechName.MetalHaulageV]: new ResearchTech(ResearchTechName.MetalHaulageV, Stats.MetalGatheringSpeed, 0,0,0),
    [ResearchTechName.MobileAssaultI]: new ResearchTech(ResearchTechName.MobileAssaultI, Stats.RiderAttack, 125,125,150),
    [ResearchTechName.MobileAssaultII]: new ResearchTech(ResearchTechName.MobileAssaultII, Stats.RiderAttack, 175,175,200),
    [ResearchTechName.MobileAssaultIII]: new ResearchTech(ResearchTechName.MobileAssaultIII, Stats.RiderAttack, 250,250,250,400),
    [ResearchTechName.MobileAssaultIV]: new ResearchTech(ResearchTechName.MobileAssaultIV, Stats.RiderAttack, 400,400,400,400,650),
    [ResearchTechName.MobileAssaultV]: new ResearchTech(ResearchTechName.MobileAssaultV, Stats.RiderAttack, 475,475,475,475,475,800),
    [ResearchTechName.MobileAssaultVI]: new ResearchTech(ResearchTechName.MobileAssaultVI, Stats.RiderAttack, 304,304,305,304,304,304,304,304,305,304,304,304),
    [ResearchTechName.MoreBedsI]: new ResearchTech(ResearchTechName.MoreBedsI, Stats.HealingCapacity, 540,1000,1800),
    [ResearchTechName.MoreBedsII]: new ResearchTech(ResearchTechName.MoreBedsII, Stats.HealingCapacity, 1100,2200,3600),
    [ResearchTechName.MoreBedsIII]: new ResearchTech(ResearchTechName.MoreBedsIII, Stats.HealingCapacity, 2200,4400,7300),
    [ResearchTechName.MoreBedsIV]: new ResearchTech(ResearchTechName.MoreBedsIV, Stats.HealingCapacity, 4300,8600,14400),
    [ResearchTechName.MoreBedsV]: new ResearchTech(ResearchTechName.MoreBedsV, Stats.HealingCapacity, 8600,17200,29200),
    [ResearchTechName.MoreBedsVI]: new ResearchTech(ResearchTechName.MoreBedsVI, Stats.HealingCapacity, 12000,24000,4000),
    [ResearchTechName.MoreBedsVII]: new ResearchTech(ResearchTechName.MoreBedsVII, Stats.HealingCapacity, 2000,4000,67000),
    [ResearchTechName.OilDrumsI]: new ResearchTech(ResearchTechName.OilDrumsI, Stats.GasProductionSpeed, 1600,3200,5350),
    [ResearchTechName.OilDrumsII]: new ResearchTech(ResearchTechName.OilDrumsII, Stats.GasProductionSpeed, 1100,2200,3650),
    [ResearchTechName.OilDrumsIII]: new ResearchTech(ResearchTechName.OilDrumsIII, Stats.GasProductionSpeed, 1350,2700,4500),
    [ResearchTechName.OilDrumsIV]: new ResearchTech(ResearchTechName.OilDrumsIV, Stats.GasProductionSpeed, 1600,3200,5350),
    [ResearchTechName.OilDrumsV]: new ResearchTech(ResearchTechName.OilDrumsV, Stats.GasProductionSpeed, 1600,3200,5350),
    [ResearchTechName.PrecisionStrikeI]: new ResearchTech(ResearchTechName.PrecisionStrikeI, Stats.HunterAttack, 125,125,150),
    [ResearchTechName.PrecisionStrikeII]: new ResearchTech(ResearchTechName.PrecisionStrikeII, Stats.HunterAttack, 175,175,200),
    [ResearchTechName.PrecisionStrikeIII]: new ResearchTech(ResearchTechName.PrecisionStrikeIII, Stats.HunterAttack, 250,250,250,400),
    [ResearchTechName.PrecisionStrikeIV]: new ResearchTech(ResearchTechName.PrecisionStrikeIV, Stats.HunterAttack, 400,400,400,400,650),
    [ResearchTechName.PrecisionStrikeV]: new ResearchTech(ResearchTechName.PrecisionStrikeV, Stats.HunterAttack, 475,475,475,475,475,800),
    [ResearchTechName.PrecisionStrikeVI]: new ResearchTech(ResearchTechName.PrecisionStrikeVI, Stats.HunterAttack, 304,304,305,304,304,304,304,304,305,304,304,304),
    [ResearchTechName.RiderDefenseI]: new ResearchTech(ResearchTechName.RiderDefenseI, Stats.RiderDefense, 125,125,150),
    [ResearchTechName.RiderDefenseII]: new ResearchTech(ResearchTechName.RiderDefenseII, Stats.RiderDefense, 175,175,200),
    [ResearchTechName.RiderDefenseIII]: new ResearchTech(ResearchTechName.RiderDefenseIII, Stats.RiderDefense, 250,250,250,400),
    [ResearchTechName.RiderDefenseIV]: new ResearchTech(ResearchTechName.RiderDefenseIV, Stats.RiderDefense, 400,400,400,400,650),
    [ResearchTechName.RiderDefenseV]: new ResearchTech(ResearchTechName.RiderDefenseV, Stats.RiderDefense, 475,475,475,475,475,800),
    [ResearchTechName.RiderDefenseVI]: new ResearchTech(ResearchTechName.RiderDefenseVI, Stats.RiderDefense, 304,304,305,304,304,304,304,304,305,304,304,304),
    [ResearchTechName.ShieldImprovementI]: new ResearchTech(ResearchTechName.ShieldImprovementI, Stats.InfantryHealth, 125,125,150),
    [ResearchTechName.ShieldImprovementII]: new ResearchTech(ResearchTechName.ShieldImprovementII, Stats.InfantryHealth, 175,175,200),
    [ResearchTechName.ShieldImprovementIII]: new ResearchTech(ResearchTechName.ShieldImprovementIII, Stats.InfantryHealth, 250,250,250,400),
    [ResearchTechName.ShieldImprovementIV]: new ResearchTech(ResearchTechName.ShieldImprovementIV, Stats.InfantryHealth, 400,400,400,400,650),
    [ResearchTechName.ShieldImprovementV]: new ResearchTech(ResearchTechName.ShieldImprovementV, Stats.InfantryHealth, 475,475,475,475,475,800),
    [ResearchTechName.ShieldImprovementVI]: new ResearchTech(ResearchTechName.ShieldImprovementVI, Stats.InfantryHealth, 304,304,305,304,304,304,304,304,305,304,304,304),
    [ResearchTechName.ShoottoKillI]: new ResearchTech(ResearchTechName.ShoottoKillI, Stats.TroopLethality, 50,50,50),
    [ResearchTechName.ShoottoKillII]: new ResearchTech(ResearchTechName.ShoottoKillII, Stats.TroopLethality, 75,75,100),
    [ResearchTechName.ShoottoKillIII]: new ResearchTech(ResearchTechName.ShoottoKillIII, Stats.TroopLethality, 100,100,100,150),
    [ResearchTechName.ShoottoKillIV]: new ResearchTech(ResearchTechName.ShoottoKillIV, Stats.TroopLethality, 175,175,175,175,300),
    [ResearchTechName.ShoottoKillV]: new ResearchTech(ResearchTechName.ShoottoKillV, Stats.TroopLethality, 200,200,200,200,200,350),
    [ResearchTechName.ShoottoKillVI]: new ResearchTech(ResearchTechName.ShoottoKillVI, Stats.TroopLethality, 127,127,127,127,127,128,127,127,127,127,127,127),
    [ResearchTechName.SortingTechI]: new ResearchTech(ResearchTechName.SortingTechI, Stats.MetalProductionSpeed, 1600,3200,5350),
    [ResearchTechName.SortingTechII]: new ResearchTech(ResearchTechName.SortingTechII, Stats.MetalProductionSpeed, 1100,2200,3650),
    [ResearchTechName.SortingTechIII]: new ResearchTech(ResearchTechName.SortingTechIII, Stats.MetalProductionSpeed, 1350,2700,4500),
    [ResearchTechName.SortingTechIV]: new ResearchTech(ResearchTechName.SortingTechIV, Stats.MetalProductionSpeed, 1600,3200,5350),
    [ResearchTechName.SortingTechV]: new ResearchTech(ResearchTechName.SortingTechV, Stats.MetalProductionSpeed, 1600,3200,5350),
    [ResearchTechName.SteadyShotI]: new ResearchTech(ResearchTechName.SteadyShotI, Stats.HunterLethality, 125,125,150),
    [ResearchTechName.SteadyShotII]: new ResearchTech(ResearchTechName.SteadyShotII, Stats.HunterLethality, 175,175,200),
    [ResearchTechName.SteadyShotIII]: new ResearchTech(ResearchTechName.SteadyShotIII, Stats.HunterLethality, 250,250,250,400),
    [ResearchTechName.SteadyShotIV]: new ResearchTech(ResearchTechName.SteadyShotIV, Stats.HunterLethality, 400,400,400,400,650),
    [ResearchTechName.SteadyShotV]: new ResearchTech(ResearchTechName.SteadyShotV, Stats.HunterLethality, 475,475,475,475,475,800),
    [ResearchTechName.SteadyShotVI]: new ResearchTech(ResearchTechName.SteadyShotVI, Stats.HunterLethality, 304,304,305,304,304,304,304,304,305,304,304,304),
    [ResearchTechName.SupplyConvoyI]: new ResearchTech(ResearchTechName.SupplyConvoyI, Stats.MaxDonationHonor, 4,4,4),
    [ResearchTechName.SupplyConvoyII]: new ResearchTech(ResearchTechName.SupplyConvoyII, Stats.MaxDonationHonor, 4,4,4),
    [ResearchTechName.SupplyConvoyIII]: new ResearchTech(ResearchTechName.SupplyConvoyIII, Stats.MaxDonationHonor, 4,4,4),
    [ResearchTechName.SupplyConvoyIV]: new ResearchTech(ResearchTechName.SupplyConvoyIV, Stats.MaxDonationHonor, 4,4,4),
    [ResearchTechName.SupplyConvoyV]: new ResearchTech(ResearchTechName.SupplyConvoyV, Stats.MaxDonationHonor, 4,4,4),
    [ResearchTechName.SurvivalTrainingI]: new ResearchTech(ResearchTechName.SurvivalTrainingI, Stats.TroopHealth, 50,50,50),
    [ResearchTechName.SurvivalTrainingII]: new ResearchTech(ResearchTechName.SurvivalTrainingII, Stats.TroopHealth, 75,75,100),
    [ResearchTechName.SurvivalTrainingIII]: new ResearchTech(ResearchTechName.SurvivalTrainingIII, Stats.TroopHealth, 100,100,100,150),
    [ResearchTechName.SurvivalTrainingIV]: new ResearchTech(ResearchTechName.SurvivalTrainingIV, Stats.TroopHealth, 175,175,175,175,300),
    [ResearchTechName.SurvivalTrainingV]: new ResearchTech(ResearchTechName.SurvivalTrainingV, Stats.TroopHealth, 200,200,200,200,200,350),
    [ResearchTechName.SurvivalTrainingVI]: new ResearchTech(ResearchTechName.SurvivalTrainingVI, Stats.TroopHealth, 127,127,127,127,127,128,127,127,127,127,127,127),
    [ResearchTechName.TechImprovementI]: new ResearchTech(ResearchTechName.TechImprovementI, Stats.ResearchSpeed, 40,80,130),
    [ResearchTechName.TechImprovementII]: new ResearchTech(ResearchTechName.TechImprovementII, Stats.ResearchSpeed, 60,120,220),
    [ResearchTechName.TechImprovementIII]: new ResearchTech(ResearchTechName.TechImprovementIII, Stats.ResearchSpeed, 100,200,300),
    [ResearchTechName.TechImprovementIV]: new ResearchTech(ResearchTechName.TechImprovementIV, Stats.ResearchSpeed, 120,240,390),
    [ResearchTechName.TechImprovementV]: new ResearchTech(ResearchTechName.TechImprovementV, Stats.ResearchSpeed, 160,320,520),
    [ResearchTechName.TechImprovementVI]: new ResearchTech(ResearchTechName.TechImprovementVI, Stats.ResearchSpeed, 180,360,610),
    [ResearchTechName.TechImprovementVII]: new ResearchTech(ResearchTechName.TechImprovementVII, Stats.ResearchSpeed, 180,360,610),
    [ResearchTechName.ToolImprovementI]: new ResearchTech(ResearchTechName.ToolImprovementI, Stats.ConstructionSpeed, 40,80,130),
    [ResearchTechName.ToolImprovementII]: new ResearchTech(ResearchTechName.ToolImprovementII, Stats.ConstructionSpeed, 60,120,220),
    [ResearchTechName.ToolImprovementIII]: new ResearchTech(ResearchTechName.ToolImprovementIII, Stats.ConstructionSpeed, 100,200,300),
    [ResearchTechName.ToolImprovementIV]: new ResearchTech(ResearchTechName.ToolImprovementIV, Stats.ConstructionSpeed, 120,240,390),
    [ResearchTechName.ToolImprovementV]: new ResearchTech(ResearchTechName.ToolImprovementV, Stats.ConstructionSpeed, 160,320,520),
    [ResearchTechName.ToolImprovementVI]: new ResearchTech(ResearchTechName.ToolImprovementVI, Stats.ConstructionSpeed, 180,360,610),
    [ResearchTechName.ToolImprovementVII]: new ResearchTech(ResearchTechName.ToolImprovementVII, Stats.ConstructionSpeed, 180,360,610),
    [ResearchTechName.TrainingRoutinesI]: new ResearchTech(ResearchTechName.TrainingRoutinesI, Stats.TrainingSpeed, 220,440,740),
    [ResearchTechName.TrainingRoutinesII]: new ResearchTech(ResearchTechName.TrainingRoutinesII, Stats.TrainingSpeed, 460,920,1520),
    [ResearchTechName.TrainingRoutinesIII]: new ResearchTech(ResearchTechName.TrainingRoutinesIII, Stats.TrainingSpeed, 680,1360,2260),
    [ResearchTechName.TrainingRoutinesIV]: new ResearchTech(ResearchTechName.TrainingRoutinesIV, Stats.TrainingSpeed, 900,1800,3000),
    [ResearchTechName.TrainingRoutinesV]: new ResearchTech(ResearchTechName.TrainingRoutinesV, Stats.TrainingSpeed, 1120,2240,3740),
    [ResearchTechName.TrainingRoutinesVI]: new ResearchTech(ResearchTechName.TrainingRoutinesVI, Stats.TrainingSpeed, 1340,2680,4480),
    [ResearchTechName.TrainingRoutinesVII]: new ResearchTech(ResearchTechName.TrainingRoutinesVII, Stats.TrainingSpeed, 1340,2680,4480),
    [ResearchTechName.TrainingYardI]: new ResearchTech(ResearchTechName.TrainingYardI, Stats.TrainingCapacity, 2,4,7),
    [ResearchTechName.TrainingYardII]: new ResearchTech(ResearchTechName.TrainingYardII, Stats.TrainingCapacity, 4,9,15),
    [ResearchTechName.TrainingYardIII]: new ResearchTech(ResearchTechName.TrainingYardIII, Stats.TrainingCapacity, 7,14,23),
    [ResearchTechName.TrainingYardIV]: new ResearchTech(ResearchTechName.TrainingYardIV, Stats.TrainingCapacity, 9,18,30),
    [ResearchTechName.TrainingYardV]: new ResearchTech(ResearchTechName.TrainingYardV, Stats.TrainingCapacity, 11,22,37),
    [ResearchTechName.TrainingYardVI]: new ResearchTech(ResearchTechName.TrainingYardVI, Stats.TrainingCapacity, 14,28,46),
    [ResearchTechName.TrainingYardVII]: new ResearchTech(ResearchTechName.TrainingYardVII, Stats.TrainingCapacity, 14,28,46),
    [ResearchTechName.WoodHaulageI]: new ResearchTech(ResearchTechName.WoodHaulageI, Stats.WoodGatheringSpeed, 800,1600,2700),
    [ResearchTechName.WoodHaulageII]: new ResearchTech(ResearchTechName.WoodHaulageII, Stats.WoodGatheringSpeed, 800,1600,2700),
    [ResearchTechName.WoodHaulageIII]: new ResearchTech(ResearchTechName.WoodHaulageIII, Stats.WoodGatheringSpeed, 1100,2200,3650),
    [ResearchTechName.WoodHaulageIV]: new ResearchTech(ResearchTechName.WoodHaulageIV, Stats.WoodGatheringSpeed, 1350,2700,4500),
    [ResearchTechName.WoodHaulageV]: new ResearchTech(ResearchTechName.WoodHaulageV, Stats.WoodGatheringSpeed, 1600,3200,5350),
    [ResearchTechName.WoodHaulageVI]: new ResearchTech(ResearchTechName.WoodHaulageVI, Stats.WoodGatheringSpeed, 1600,3200,5350)
} as const;
